import { Inter } from "next/font/google";
import "@/ui/globals.css";
import Header from "./header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}</body>
    </html>
  );
}
